//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;

namespace OpenDentBusiness.Crud{
	public class DiscountPlanCrud {
		///<summary>Gets one DiscountPlan object from the database using the primary key.  Returns null if not found.</summary>
		public static DiscountPlan SelectOne(long discountPlanNum){
			string command="SELECT * FROM discountplan "
				+"WHERE DiscountPlanNum = "+POut.Long(discountPlanNum);
			List<DiscountPlan> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one DiscountPlan object from the database using a query.</summary>
		public static DiscountPlan SelectOne(string command){
			if(RemotingClient.RemotingRole==RemotingRole.ClientWeb) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<DiscountPlan> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of DiscountPlan objects from the database using a query.</summary>
		public static List<DiscountPlan> SelectMany(string command){
			if(RemotingClient.RemotingRole==RemotingRole.ClientWeb) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<DiscountPlan> list=TableToList(Db.GetTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<DiscountPlan> TableToList(DataTable table){
			List<DiscountPlan> retVal=new List<DiscountPlan>();
			DiscountPlan discountPlan;
			foreach(DataRow row in table.Rows) {
				discountPlan=new DiscountPlan();
				discountPlan.DiscountPlanNum= PIn.Long  (row["DiscountPlanNum"].ToString());
				discountPlan.Description    = PIn.String(row["Description"].ToString());
				discountPlan.FeeSchedNum    = PIn.Long  (row["FeeSchedNum"].ToString());
				discountPlan.DefNum         = PIn.Long  (row["DefNum"].ToString());
				discountPlan.IsHidden       = PIn.Bool  (row["IsHidden"].ToString());
				retVal.Add(discountPlan);
			}
			return retVal;
		}

		///<summary>Converts a list of DiscountPlan into a DataTable.</summary>
		public static DataTable ListToTable(List<DiscountPlan> listDiscountPlans,string tableName="") {
			if(string.IsNullOrEmpty(tableName)) {
				tableName="DiscountPlan";
			}
			DataTable table=new DataTable(tableName);
			table.Columns.Add("DiscountPlanNum");
			table.Columns.Add("Description");
			table.Columns.Add("FeeSchedNum");
			table.Columns.Add("DefNum");
			table.Columns.Add("IsHidden");
			foreach(DiscountPlan discountPlan in listDiscountPlans) {
				table.Rows.Add(new object[] {
					POut.Long  (discountPlan.DiscountPlanNum),
					            discountPlan.Description,
					POut.Long  (discountPlan.FeeSchedNum),
					POut.Long  (discountPlan.DefNum),
					POut.Bool  (discountPlan.IsHidden),
				});
			}
			return table;
		}

		///<summary>Inserts one DiscountPlan into the database.  Returns the new priKey.</summary>
		public static long Insert(DiscountPlan discountPlan){
			if(DataConnection.DBtype==DatabaseType.Oracle) {
				discountPlan.DiscountPlanNum=DbHelper.GetNextOracleKey("discountplan","DiscountPlanNum");
				int loopcount=0;
				while(loopcount<100){
					try {
						return Insert(discountPlan,true);
					}
					catch(Oracle.ManagedDataAccess.Client.OracleException ex){
						if(ex.Number==1 && ex.Message.ToLower().Contains("unique constraint") && ex.Message.ToLower().Contains("violated")){
							discountPlan.DiscountPlanNum++;
							loopcount++;
						}
						else{
							throw ex;
						}
					}
				}
				throw new ApplicationException("Insert failed.  Could not generate primary key.");
			}
			else {
				return Insert(discountPlan,false);
			}
		}

		///<summary>Inserts one DiscountPlan into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(DiscountPlan discountPlan,bool useExistingPK){
			if(!useExistingPK && PrefC.RandomKeys) {
				discountPlan.DiscountPlanNum=ReplicationServers.GetKey("discountplan","DiscountPlanNum");
			}
			string command="INSERT INTO discountplan (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="DiscountPlanNum,";
			}
			command+="Description,FeeSchedNum,DefNum,IsHidden) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(discountPlan.DiscountPlanNum)+",";
			}
			command+=
				 "'"+POut.String(discountPlan.Description)+"',"
				+    POut.Long  (discountPlan.FeeSchedNum)+","
				+    POut.Long  (discountPlan.DefNum)+","
				+    POut.Bool  (discountPlan.IsHidden)+")";
			if(useExistingPK || PrefC.RandomKeys) {
				Db.NonQ(command);
			}
			else {
				discountPlan.DiscountPlanNum=Db.NonQ(command,true,"DiscountPlanNum","discountPlan");
			}
			return discountPlan.DiscountPlanNum;
		}

		///<summary>Inserts one DiscountPlan into the database.  Returns the new priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(DiscountPlan discountPlan){
			if(DataConnection.DBtype==DatabaseType.MySql) {
				return InsertNoCache(discountPlan,false);
			}
			else {
				if(DataConnection.DBtype==DatabaseType.Oracle) {
					discountPlan.DiscountPlanNum=DbHelper.GetNextOracleKey("discountplan","DiscountPlanNum"); //Cacheless method
				}
				return InsertNoCache(discountPlan,true);
			}
		}

		///<summary>Inserts one DiscountPlan into the database.  Provides option to use the existing priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(DiscountPlan discountPlan,bool useExistingPK){
			bool isRandomKeys=Prefs.GetBoolNoCache(PrefName.RandomPrimaryKeys);
			string command="INSERT INTO discountplan (";
			if(!useExistingPK && isRandomKeys) {
				discountPlan.DiscountPlanNum=ReplicationServers.GetKeyNoCache("discountplan","DiscountPlanNum");
			}
			if(isRandomKeys || useExistingPK) {
				command+="DiscountPlanNum,";
			}
			command+="Description,FeeSchedNum,DefNum,IsHidden) VALUES(";
			if(isRandomKeys || useExistingPK) {
				command+=POut.Long(discountPlan.DiscountPlanNum)+",";
			}
			command+=
				 "'"+POut.String(discountPlan.Description)+"',"
				+    POut.Long  (discountPlan.FeeSchedNum)+","
				+    POut.Long  (discountPlan.DefNum)+","
				+    POut.Bool  (discountPlan.IsHidden)+")";
			if(useExistingPK || isRandomKeys) {
				Db.NonQ(command);
			}
			else {
				discountPlan.DiscountPlanNum=Db.NonQ(command,true,"DiscountPlanNum","discountPlan");
			}
			return discountPlan.DiscountPlanNum;
		}

		///<summary>Updates one DiscountPlan in the database.</summary>
		public static void Update(DiscountPlan discountPlan){
			string command="UPDATE discountplan SET "
				+"Description    = '"+POut.String(discountPlan.Description)+"', "
				+"FeeSchedNum    =  "+POut.Long  (discountPlan.FeeSchedNum)+", "
				+"DefNum         =  "+POut.Long  (discountPlan.DefNum)+", "
				+"IsHidden       =  "+POut.Bool  (discountPlan.IsHidden)+" "
				+"WHERE DiscountPlanNum = "+POut.Long(discountPlan.DiscountPlanNum);
			Db.NonQ(command);
		}

		///<summary>Updates one DiscountPlan in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.  Returns true if an update occurred.</summary>
		public static bool Update(DiscountPlan discountPlan,DiscountPlan oldDiscountPlan){
			string command="";
			if(discountPlan.Description != oldDiscountPlan.Description) {
				if(command!=""){ command+=",";}
				command+="Description = '"+POut.String(discountPlan.Description)+"'";
			}
			if(discountPlan.FeeSchedNum != oldDiscountPlan.FeeSchedNum) {
				if(command!=""){ command+=",";}
				command+="FeeSchedNum = "+POut.Long(discountPlan.FeeSchedNum)+"";
			}
			if(discountPlan.DefNum != oldDiscountPlan.DefNum) {
				if(command!=""){ command+=",";}
				command+="DefNum = "+POut.Long(discountPlan.DefNum)+"";
			}
			if(discountPlan.IsHidden != oldDiscountPlan.IsHidden) {
				if(command!=""){ command+=",";}
				command+="IsHidden = "+POut.Bool(discountPlan.IsHidden)+"";
			}
			if(command==""){
				return false;
			}
			command="UPDATE discountplan SET "+command
				+" WHERE DiscountPlanNum = "+POut.Long(discountPlan.DiscountPlanNum);
			Db.NonQ(command);
			return true;
		}

		///<summary>Returns true if Update(DiscountPlan,DiscountPlan) would make changes to the database.
		///Does not make any changes to the database and can be called before remoting role is checked.</summary>
		public static bool UpdateComparison(DiscountPlan discountPlan,DiscountPlan oldDiscountPlan) {
			if(discountPlan.Description != oldDiscountPlan.Description) {
				return true;
			}
			if(discountPlan.FeeSchedNum != oldDiscountPlan.FeeSchedNum) {
				return true;
			}
			if(discountPlan.DefNum != oldDiscountPlan.DefNum) {
				return true;
			}
			if(discountPlan.IsHidden != oldDiscountPlan.IsHidden) {
				return true;
			}
			return false;
		}

		///<summary>Deletes one DiscountPlan from the database.</summary>
		public static void Delete(long discountPlanNum){
			string command="DELETE FROM discountplan "
				+"WHERE DiscountPlanNum = "+POut.Long(discountPlanNum);
			Db.NonQ(command);
		}

	}
}